services:
  pai4-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      PAI4_DB_PATH: /opt/pai4/data/app.db
      PAI4_ADMIN_USERNAME: ${PAI4_ADMIN_USERNAME:-admin}
      PAI4_MEMBER_USERNAME: ${PAI4_MEMBER_USERNAME:-member}
      PAI4_ADMIN_PASSWORD: ${PAI4_ADMIN_PASSWORD:?pai4}
      PAI4_MEMBER_PASSWORD: ${PAI4_MEMBER_PASSWORD:?pai}
    ports:
      - "5000:5000"
    volumes:
      - ../data:/opt/pai4/data
